services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - HOST=localhost
      - PORT=8000
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - DB_HOST=database
      - DB_PORT=5432
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb

  adminer:
    image: adminer
    restart: always
    ports:
      - "8001:8080"
