services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8001:8080"
